name: MacOS
on:
  push:
    branches:
      - '*'
    paths:
      - '**.c'
      - '**.h'
      - 'compat/*'
      - '.github/workflows/MacOS.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.c'
      - '**.h'
      - 'compat/*'
      - '.github/workflows/MacOS.yml'



jobs:
  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./build_deps.sh
    - run: ./build.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: out


